pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        TF_IN_AUTOMATION      = '1'
    }
    stages {
        stage('Terraform deploy') {
            //echo "using terraform to create RG in Azure"
            steps {
                withCredentials([azureServicePrincipal('contributor-role')]) {
                {
                sh '''
                cd terraform_rg
                terraform init
                terraform plan
                terraform apply
                '''                
            }
        }
    }
        stage('clean workspace') {
            steps{
            sh 'rm -rf .terraform'
            cleanWs()
            }
              
        }
    }
}
