pipeline {
    agent {
        docker { image 'zenika/terraform-azure-cli:latest' }
    }
    
    stages {
        stage('clean workspace') {
            steps{
            cleanWs()
            }
              
        }
        stage('Initial Build') {
            steps {
                echo 'Building..'
                sh''' 
                  cd bash
                  chmod +x sample.sh
                  terraform --version
                  bash sample.sh
                    '''
                }
            }
        }
        stage('clean workspace') {
            steps{
        
            cleanWs()
            }
              
        }
    }    

