pipeline {
    agent any

    stages {
        stage('Initial Build') {
            steps {
                echo 'Building..'

                sh '''
                ls -la
                cd bash
                chmod +x sample.sh
                bash sample.sh
                '''
            }
        }
    }
        post {
        // Clean after build
        always {
            cleanWs()
              
            }

        
    }
}