pipeline {
    agent {
        docker { image 'zenika/terraform-azure-cli:latest' }
       

    stages {
        stage('Initial Build') {
            steps {
                echo 'Building..'
                sh''' 
                  cd bash
                  chmod +x sample.sh
                  bash sample.sh
                   
                '''
                
            }
        }
    }
        post {
        // Clean after build
        always {
            cleanWs()
              
            }

        
    }
}
}